project:
  type: website
  resources: Index.html
  output-dir: docs

website:
  title: "TU Delft R Café"
  site-url: https://delft-rcafe.github.io/home/
  favicon: img/logo.png
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    left: "&copy; CC-BY TU Delft R Café"
  
  
  navbar: 
    logo: img/logo.png
    href: https://delft-rcafe.github.io/home/
    right:
      - icon: github
        href:  https://github.com/Delft-RCafe/home/

    left:
      - href: index.qmd
        text: Home
      - text: Plot-a-thon
        menu: 
          - text: "About"
            href: plotathon/about.qmd
          - text: "FAQ"
            href: plotathon/faq.qmd
          - text: "2023"
            href: plotathon/2023-plotathon.qmd
format: 
  html:
    code-tools: true
    fig-cap-location: bottom
    self-contained: true
    theme: 
        light: rcafe-theme.scss
        dark: rcafe-dark.scss